#################################################################
#        This is a yaml file to configure all parameters.       #
#################################################################

# load label and data
train_label_path: '../data/faceDR'
train_start: 1223                    # min 1223
train_end: 3221                      # max 3221

test_label_path: '../data/faceDS'
test_start: 3223                     # min 3223
test_end: 4222                       # max 5222
label: 7                             # 4-sex, 7-age

data_path: '../data/jpg/'
dim_reduction_algorithm: 'lda'       # lda, pca
n_components: 2                      # 1 is for sex label and lda

# classifier
classifier_algorithm: 'knn'          # knn, svm
n_neighbors: 10                       # for knn
C: 2                                 # for svm
kernel: 'rbf'                        # for svm, rbf or linear
gamma: 10                            # for svm
decision_function_shape: 'ovr'       # for svm, ovr or ovo
cv: 3                                # for K-fold cross-validation
