#################################################################
#        This is a yaml file to configure all parameters.       #
#################################################################

# load label and data
train_label_path: '../data/faceDR'
train_start: 1223
train_end: 3222

test_label_path: '../data/faceDS'
test_start: 3223
test_end: 5222
label: 4                             # 4-sex, 7-age

data_path: '../data/jpg/'
dim_reduction_algorithm: 'pca'       # lda, pca
n_components: 1                      # 1 is for sex label and lda

# classifier
classifier_algorithm: 'svm'          # knn, svm
n_neighbors: 5                       # for knn
C: 2                                 # for svm
kernel: 'rbf'                        # for svm, rbf or linear
gamma: 10                            # for svm
decision_function_shape: 'ovr'       # for svm, ovr or ovo

