#################################################################
#        This is a yaml file to configure all parameters.       #
#################################################################

# load label
train_label_path: '../data/faceDR'
train_label_start: 1234
train_label_end: 1303

test_label_path: '../data/faceDR'
test_label_start: 1304
test_label_end: 1333
label: 4                             # 4-sex, 7-age

# load data
data_path: '../data/jpg/'
train_data_start: 1234
train_data_end: 1303

test_data_start: 1304
test_data_end: 1333
dim_reduction_algorithm: 'lda'       # LDA, PCA
n_components: 1                      # 1 is for sex label and lda

# classifier
classifier_algorithm: 'knn'          # KNN, SVM
n_neighbors: 5                       # for knn
C: 2                                 # for svm
kernel: 'rbf'                        # for svm, rbf or linear
gamma: 10                            # for svm
decision_function_shape: 'ovr'       # for svm, ovr or ovo

